apiVersion: v1
kind: PersistentVolume
metadata:
  name: helm-postgres-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.142.0.4
    path: /k8sNFS
